using System.Net;
using DataBro.Modules.Identity.Application;
using DataBro.Platform.Abstractions;
using Microsoft.Extensions.Options;

namespace DataBro.Modules.Identity.Infrastructure.Auth;

/// <summary>Where a confirmation link points, and in which language it is written.</summary>
public sealed class IdentityEmailOptions
{
    public const string SectionName = "Identity:Emails";

    /// <summary>
    /// The app that handles the confirmation link. The <b>app</b>, not the API: a person clicking a
    /// link expects a page, and the API would hand them raw JSON.
    /// </summary>
    public string AppBaseUrl { get; set; } = "http://localhost:3001";

    /// <summary>`en` or `id`. Until a locale is stored per user, every email is in the default.</summary>
    public string DefaultLocale { get; set; } = "en";

    /// <summary>
    /// Whether an unconfirmed address may sign in. <b>Defaults to true</b> — secure by default, and
    /// deliberately not turned off in development: a rule that is only enforced in production is a
    /// rule nobody has tested.
    /// </summary>
    public bool RequireConfirmedEmail { get; set; } = true;
}

/// <summary>
/// Composes Identity's emails and hands them to the transport.
///
/// <para>
/// Templates live here as C# strings rather than files. Two emails do not justify a template engine,
/// and a `.cshtml` that has to be copied into a container is a deployment step waiting to be
/// forgotten. Revisit when there is a fifth.
/// </para>
/// <para>
/// Localised per CLAUDE.md rule 19 — the rule governs UI chrome, and an email is chrome that arrives
/// by post. There is no per-user locale column yet, so the language comes from configuration; the
/// structure is what matters, because adding the column later then changes one argument.
/// </para>
/// </summary>
public sealed class IdentityEmails(
    IEmailSender sender,
    IOptions<IdentityEmailOptions> options) : IIdentityEmails
{
    private readonly IdentityEmailOptions _options = options.Value;

    public Task SendEmailConfirmationAsync(
        string email, string displayName, Guid userId, string token, CancellationToken ct = default)
    {
        var link = Link("verify-email", userId, token);
        var name = string.IsNullOrWhiteSpace(displayName) ? email : displayName;
        var indonesian = IsIndonesian;

        var (subject, greeting, lead, action, ignore) = indonesian
            ? ("Konfirmasi alamat email Anda",
               $"Halo {name},",
               "Terima kasih telah mendaftar di DataBro. Konfirmasi alamat email Anda untuk mulai belajar.",
               "Konfirmasi email",
               "Jika Anda tidak membuat akun ini, abaikan email ini.")
            : ("Confirm your email address",
               $"Hi {name},",
               "Thanks for joining DataBro. Confirm your email address to start learning.",
               "Confirm email",
               "If you did not create this account, you can ignore this email.");

        return sender.SendAsync(
            new EmailMessage(email, subject, Html(indonesian, greeting, lead, action, link, ignore),
                Text(greeting, lead, action, link, ignore)),
            ct);
    }

    public Task SendPasswordResetAsync(
        string email, string displayName, Guid userId, string token, CancellationToken ct = default)
    {
        var link = Link("reset-password", userId, token);
        var name = string.IsNullOrWhiteSpace(displayName) ? email : displayName;
        var indonesian = IsIndonesian;

        var (subject, greeting, lead, action, ignore) = indonesian
            ? ("Setel ulang kata sandi Anda",
               $"Halo {name},",
               "Kami menerima permintaan untuk menyetel ulang kata sandi Anda. Tautan ini berlaku selama satu hari.",
               "Setel ulang kata sandi",
               "Jika Anda tidak meminta ini, abaikan email ini. Kata sandi Anda tidak berubah.")
            : ("Reset your password",
               $"Hi {name},",
               "We received a request to reset your password. This link is valid for one day.",
               "Reset password",
               "If you did not request this, ignore this email. Your password has not changed.");

        // The reassurance in the last line is the point of sending anything at all to someone who
        // did not ask: it tells them nothing has happened yet, so an unexpected email is not alarming.
        return sender.SendAsync(
            new EmailMessage(email, subject, Html(indonesian, greeting, lead, action, link, ignore),
                Text(greeting, lead, action, link, ignore)),
            ct);
    }

    private bool IsIndonesian =>
        _options.DefaultLocale.StartsWith("id", StringComparison.OrdinalIgnoreCase);

    /// <summary>
    /// Builds a link into the app.
    ///
    /// <para>
    /// The token is generated by ASP.NET Core Identity and is <b>not URL-safe</b>: it is base64 with
    /// `+` and `/` in it, and an unencoded `+` arrives at the server as a space. That fails for a
    /// fraction of users and works for whoever tests it once, which is why encoding happens here,
    /// in one place, rather than at each call site.
    /// </para>
    /// </summary>
    private string Link(string page, Guid userId, string token) =>
        $"{_options.AppBaseUrl.TrimEnd('/')}/{page}" +
        $"?userId={Uri.EscapeDataString(userId.ToString())}" +
        $"&token={Uri.EscapeDataString(token)}";

    /// <summary>
    /// The shared shell. Every interpolated value is HTML-encoded: a display name is user input and
    /// this puts it into markup, and an email client is a HTML renderer like any other.
    /// </summary>
    private static string Html(
        bool indonesian, string greeting, string lead, string action, string link, string footer) =>
        $"""
        <!doctype html>
        <html lang="{(indonesian ? "id" : "en")}">
          <body style="margin:0;padding:24px;background:#f6f7f9;font-family:system-ui,-apple-system,'Segoe UI',sans-serif;color:#1c2530;">
            <div style="max-width:520px;margin:0 auto;background:#ffffff;border-radius:12px;padding:32px;">
              <p style="margin:0 0 16px;font-size:16px;">{WebUtility.HtmlEncode(greeting)}</p>
              <p style="margin:0 0 24px;line-height:1.6;">{WebUtility.HtmlEncode(lead)}</p>
              <p style="margin:0 0 24px;">
                <a href="{WebUtility.HtmlEncode(link)}"
                   style="display:inline-block;background:#2f6df6;color:#ffffff;text-decoration:none;padding:12px 20px;border-radius:8px;font-weight:600;">
                  {WebUtility.HtmlEncode(action)}
                </a>
              </p>
              <p style="margin:0;font-size:13px;color:#5b6672;line-height:1.6;">{WebUtility.HtmlEncode(footer)}</p>
            </div>
          </body>
        </html>
        """;

    /// <summary>
    /// The plain-text alternative. The link appears in full: a text client cannot click a button,
    /// and "open the HTML version" is not a fallback.
    /// </summary>
    private static string Text(string greeting, string lead, string action, string link, string footer) =>
        $"""
        {greeting}

        {lead}

        {action}: {link}

        {footer}
        """;
}
