using System.Net;
using DataBro.Modules.Identity.Application;
using DataBro.Platform.Abstractions;
using Microsoft.Extensions.Options;

namespace DataBro.Modules.Identity.Infrastructure.Auth;

/// <summary>Where a confirmation link points, and in which language it is written.</summary>
public sealed class IdentityEmailOptions
{
    public const string SectionName = "Identity:Emails";

    /// <summary>
    /// The app that handles the confirmation link. The <b>app</b>, not the API: a person clicking a
    /// link expects a page, and the API would hand them raw JSON.
    /// </summary>
    public string AppBaseUrl { get; set; } = "http://localhost:3001";

    /// <summary>`en` or `id`. Until a locale is stored per user, every email is in the default.</summary>
    public string DefaultLocale { get; set; } = "en";
}

/// <summary>
/// Composes Identity's emails and hands them to the transport.
///
/// <para>
/// Templates live here as C# strings rather than files. Two emails do not justify a template engine,
/// and a `.cshtml` that has to be copied into a container is a deployment step waiting to be
/// forgotten. Revisit when there is a fifth.
/// </para>
/// <para>
/// Localised per CLAUDE.md rule 19 — the rule governs UI chrome, and an email is chrome that arrives
/// by post. There is no per-user locale column yet, so the language comes from configuration; the
/// structure is what matters, because adding the column later then changes one argument.
/// </para>
/// </summary>
public sealed class IdentityEmails(
    IEmailSender sender,
    IOptions<IdentityEmailOptions> options) : IIdentityEmails
{
    private readonly IdentityEmailOptions _options = options.Value;

    public Task SendEmailConfirmationAsync(
        string email, string displayName, Guid userId, string token, CancellationToken ct = default)
    {
        // The token is generated by ASP.NET Core Identity and is not URL-safe on its own — it is
        // base64 with `+` and `/` in it, and an unencoded `+` arrives at the server as a space,
        // which is a confirmation that silently fails for a fraction of users.
        var link =
            $"{_options.AppBaseUrl.TrimEnd('/')}/verify-email" +
            $"?userId={Uri.EscapeDataString(userId.ToString())}" +
            $"&token={Uri.EscapeDataString(token)}";

        var name = string.IsNullOrWhiteSpace(displayName) ? email : displayName;
        var indonesian = _options.DefaultLocale.StartsWith("id", StringComparison.OrdinalIgnoreCase);

        var (subject, greeting, lead, action, ignore) = indonesian
            ? ("Konfirmasi alamat email Anda",
               $"Halo {name},",
               "Terima kasih telah mendaftar di DataBro. Konfirmasi alamat email Anda untuk mulai belajar.",
               "Konfirmasi email",
               "Jika Anda tidak membuat akun ini, abaikan email ini.")
            : ("Confirm your email address",
               $"Hi {name},",
               "Thanks for joining DataBro. Confirm your email address to start learning.",
               "Confirm email",
               "If you did not create this account, you can ignore this email.");

        // HtmlEncode on every interpolated value: a display name is user input, and it is being put
        // into markup. An email client is a HTML renderer like any other.
        var html = $"""
            <!doctype html>
            <html lang="{(indonesian ? "id" : "en")}">
              <body style="margin:0;padding:24px;background:#f6f7f9;font-family:system-ui,-apple-system,'Segoe UI',sans-serif;color:#1c2530;">
                <div style="max-width:520px;margin:0 auto;background:#ffffff;border-radius:12px;padding:32px;">
                  <p style="margin:0 0 16px;font-size:16px;">{WebUtility.HtmlEncode(greeting)}</p>
                  <p style="margin:0 0 24px;line-height:1.6;">{WebUtility.HtmlEncode(lead)}</p>
                  <p style="margin:0 0 24px;">
                    <a href="{WebUtility.HtmlEncode(link)}"
                       style="display:inline-block;background:#2f6df6;color:#ffffff;text-decoration:none;padding:12px 20px;border-radius:8px;font-weight:600;">
                      {WebUtility.HtmlEncode(action)}
                    </a>
                  </p>
                  <p style="margin:0;font-size:13px;color:#5b6672;line-height:1.6;">{WebUtility.HtmlEncode(ignore)}</p>
                </div>
              </body>
            </html>
            """;

        // The link appears in full in the text part. A text-only client cannot click a button, and
        // "open the HTML version" is not a fallback.
        var text = $"""
            {greeting}

            {lead}

            {action}: {link}

            {ignore}
            """;

        return sender.SendAsync(new EmailMessage(email, subject, html, text), ct);
    }
}
