<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" Version="6.0.2" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.12.0" />
    <PackageReference Include="NetArchTest.Rules" Version="1.3.2" />
    <PackageReference Include="xunit" Version="2.9.2" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.8.2" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Shared\DataBro.Platform\DataBro.Platform.csproj" />
    <ProjectReference Include="..\..\src\Modules\Identity\DataBro.Modules.Identity.Domain\DataBro.Modules.Identity.Domain.csproj" />
    <ProjectReference Include="..\..\src\Modules\Identity\DataBro.Modules.Identity.Application\DataBro.Modules.Identity.Application.csproj" />
    <ProjectReference Include="..\..\src\Modules\Identity\DataBro.Modules.Identity.Infrastructure\DataBro.Modules.Identity.Infrastructure.csproj" />
    <ProjectReference Include="..\..\src\Modules\Identity\DataBro.Modules.Identity.Api\DataBro.Modules.Identity.Api.csproj" />
    <ProjectReference Include="..\..\src\Modules\Content\DataBro.Modules.Content.Domain\DataBro.Modules.Content.Domain.csproj" />
    <ProjectReference Include="..\..\src\Modules\Content\DataBro.Modules.Content.Application\DataBro.Modules.Content.Application.csproj" />
    <ProjectReference Include="..\..\src\Modules\Content\DataBro.Modules.Content.Infrastructure\DataBro.Modules.Content.Infrastructure.csproj" />
    <ProjectReference Include="..\..\src\Modules\Content\DataBro.Modules.Content.Api\DataBro.Modules.Content.Api.csproj" />
    <ProjectReference Include="..\..\src\Modules\Media\DataBro.Modules.Media.Domain\DataBro.Modules.Media.Domain.csproj" />
    <ProjectReference Include="..\..\src\Modules\Media\DataBro.Modules.Media.Application\DataBro.Modules.Media.Application.csproj" />
    <ProjectReference Include="..\..\src\Modules\Media\DataBro.Modules.Media.Infrastructure\DataBro.Modules.Media.Infrastructure.csproj" />
    <ProjectReference Include="..\..\src\Modules\Media\DataBro.Modules.Media.Api\DataBro.Modules.Media.Api.csproj" />
    <ProjectReference Include="..\..\src\Modules\Search\DataBro.Modules.Search.Domain\DataBro.Modules.Search.Domain.csproj" />
    <ProjectReference Include="..\..\src\Modules\Search\DataBro.Modules.Search.Application\DataBro.Modules.Search.Application.csproj" />
    <ProjectReference Include="..\..\src\Modules\Search\DataBro.Modules.Search.Infrastructure\DataBro.Modules.Search.Infrastructure.csproj" />
    <ProjectReference Include="..\..\src\Modules\Search\DataBro.Modules.Search.Api\DataBro.Modules.Search.Api.csproj" />
  </ItemGroup>

</Project>
