<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\DataBro.Modules.Search.Application\DataBro.Modules.Search.Application.csproj" />
    <ProjectReference Include="..\DataBro.Modules.Search.Infrastructure\DataBro.Modules.Search.Infrastructure.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
